name: Hourly Discord Boss Alert

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  trigger-supabase-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Discord Alert Edge Function
        run: |
          curl -i -X POST 'https://farewcumdwtdpfcycsmi.supabase.co/functions/v1/discord-hourly-alert' \
            -H 'Authorization: Bearer sb_publishable_2R9yxtZpeeXq1L47fpT_7g_8juD6uZq' \
            -H 'Content-Type: application/json'
